/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientReadInterface.java
 *
 * Created on Oct 24, 2012, 3:33:33 PM
 */

package quorumreplication;
import java.awt.Color;
import java.rmi.*;
import java.rmi.registry.*;
import java.rmi.server.*;
import java.net.*;
import java.sql.*;
import java.io.*;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.*;
import javax.swing.JOptionPane;
/**
 *
 * @author SHAHNA
 */
public class ClientReadInterface extends javax.swing.JFrame implements ReceiveMessageInterface
{
String address;
Registry registry;

public int writenewrecord(int vno,String sid,String sname,String saddress,int phone) throws RemoteException,SQLException
{
    return 0;
}
public void receiveVersion(String x,String y) throws RemoteException,SQLException
{
}
public String receiveVersion1(String x,String y) throws RemoteException,SQLException
{
    return null;
}
  public String selectrecords(String x) throws RemoteException,SQLException
  {
  return null;
  }
  public int updaterecords(String rollno,String[] array) throws RemoteException,SQLException
  {
  return 0;
  }

public void display(String[] array) throws RemoteException
{
    

 System.out.println("version="+array[0]);
System.out.println("id="+array[1]);
System.out.println("name="+array[2]);
System.out.println("address="+array[3]);
System.out.println("phone="+array[4]);
Vector columnNames=new Vector();
Vector data=new Vector();
JPanel jp=new JPanel();
columnNames.addElement("Roll no.");
columnNames.addElement("Name");
columnNames.addElement("Address");
columnNames.addElement("Phone number");
Vector row=new Vector(4);
row.addElement(array[1]);
row.addElement(array[2]);
row.addElement(array[3]);
row.addElement(array[4]);
data.addElement(row);
JTable table=new JTable(data,columnNames);
TableColumn col;
for(int i=0;i<table.getColumnCount();i++)
{
    col=table.getColumnModel().getColumn(i);
    col.setMaxWidth(250);
}
JScrollPane scrollpane=new JScrollPane(table);
jp.add(scrollpane);
JFrame jf=new JFrame();
jf.add(jp);
jf.setSize(600,400);
jf.setVisible(true);





/*String s=array[2];
jLabel3.setBackground(Color.CYAN);
    jTextField1.setText("s");
     jTextField2.setBackground(Color.BLACK);
/*if(record!=null)
    {
     
    String a=record[3];
    jTextField1.setText(a);
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {
        {record[1], record[2], record[3], a},

    },
    new String [] {
        "ROLL NUMBER", "NAME", "ADDRESS", "PHONE NUMBER"
    }
));
    }
    else
    {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
    },
    new String [] {
        "ROLL NUMBER", "NAME", "ADDRESS", "PHONE NUMBER"
    }
));
    }

*/
}

    /** Creates new form ClientReadInterface */
    public ClientReadInterface() {
        initComponents();
          setSize(1200,968);
          try
          {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con=DriverManager.getConnection("jdbc:odbc:quorumdsn","usr","pwd");
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select st_id from student_records");
                while(rs.next())
                {
                    jComboBox1.addItem(rs.getString(1));
                }
          }
          catch(Exception e)
          {

          }
          try{
  address = (InetAddress.getLocalHost()).toString();
  }
  catch(Exception e){
  System.out.println("can't get inet address.");
  }
  int port=3233;
  System.out.println("this address=" + address +  ",port=" + port);
  try{
  registry = LocateRegistry.createRegistry(port);
  registry.rebind("rmiClient", this);
  }
  catch(RemoteException e){
  System.out.println("remote exception"+ e);
  }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("STORAGE AND RETRIEVAL OF INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 1070, 50);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("USING QUORUM_BASED TECHNIQUE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 60, 930, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Choose the Roll No :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 230, 190, 30);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(550, 230, 150, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back to Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(970, 430, 200, 70);

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("READ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 220, 150, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHAHNA\\Pictures\\sea.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -70, 1260, 1080);

        jTextField2.setBackground(new java.awt.Color(102, 255, 102));
        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(90, 550, 59, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ReceiveMessageInterface rmiServer;
  Registry registry,registry1;
  //String serverAddress="169.254.52.254";
 // String serverAddress="192.168.56.1";
  String serverAddress="127.0.0.1";
  String serverPort="3232";
   String rollno=jComboBox1.getSelectedItem().toString();
         try
  {
  registry=LocateRegistry.getRegistry
  (serverAddress,(new Integer(serverPort)).intValue());
  rmiServer=(ReceiveMessageInterface)(registry.lookup("rmiServer"));  // call the remote method
  rmiServer.receiveVersion(rollno, "yes");
  }
  catch(RemoteException e){
  e.printStackTrace();
  }
  catch(NotBoundException e){
  System.err.println(e);
  }
   catch(Exception e)
   {
      System.err.println(e);
   }
JOptionPane.showMessageDialog(null,"You can read the details of particular student!!!");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          new ClientInterface().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientReadInterface().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}







