/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientInterface.java
 *
 * Created on Oct 24, 2012, 1:16:24 PM
 */

package quorumreplication;

/**
 *
 * @author SHAHNA
 */
public class ClientInterface extends javax.swing.JFrame {

    /** Creates new form ClientInterface */
    public ClientInterface() {
        initComponents();
        setSize(1200,968);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36));
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("STORAGE AND RETRIVAL OF INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 0, 1060, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Choose an option :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 360, 151, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 450, 180, 60);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Read", "Write" }));
        jComboBox1.setToolTipText("Select yuor choice");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(640, 360, 140, 50);

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36));
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("USING QUORUM-BASED TECHNIQUE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 80, 870, 60);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(440, 330, 370, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\SHAHNA\\Pictures\\sea.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1910, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
     //   jComboBox1.addItem("Read");
      //  jComboBox1.addItem("Write");

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ch=jComboBox1.getSelectedItem().toString();
        if(ch.equals("Read"))
        {
           new ClientReadInterface().setVisible(true);
        }
        else if(ch.equals("Write"))
        {
           new ClientWriteInterface().setVisible(true);
        }
        else if(ch.equals("Update"))
        {
            new ClientUpdateInterface().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
