/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientInterface.java
 *
 * Created on Oct 24, 2012, 2:39:43 PM
 */

package quorumreplication;

/**
 *
 * @author SHAHNA
 */
public class Write extends javax.swing.JFrame {

    /** Creates new form ClientInterface */
    public Write() {
        initComponents();
        setSize(1024,768);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36));
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("STORAGE AND RETRIEVAL OF INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 1070, 50);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36));
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("USING QUORUM_BASED TECHNIQUE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 60, 930, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Choose Your Choice :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 390, 180, 40);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Read", "Write" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(580, 390, 200, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 490, 140, 60);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -150, 1250, 1240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
